# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = { };
in
{
  "@anthropic-ai/claude-code" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "1.0.81";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.81.tgz";
      sha512 = "kiRgAhQ2vuodkHDAZjuR0aaNchl9SZLq0QF46JKsOw0Ik1eyEN0tdsF++AV//Ub1j4iS1fGIrU10uE7aqFfKYw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  ccusage = nodeEnv.buildNodePackage {
    name = "ccusage";
    packageName = "ccusage";
    version = "15.9.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-15.9.5.tgz";
      sha512 = "qovG9S4rP24w70PanPDE32cTrc1UACgqJiDEMsJZVOvMqn8wKxM+DSQOu2EsvXSeEtbntacOQFhpEPECduZaMQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Usage analysis tool for Claude Code";
      homepage = "https://github.com/ryoppippi/ccusage#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
