PreToolUse:
  - matcher: "WebFetch"
    conditions:
      - type: url_starts_with
        value: "https://github.com"
    actions:
      - type: output
        message: "WebFetchではなく、`gh`コマンド経由で情報を取得しましょう"

PostToolUse:

Notification:

UserPromptSubmit:

Stop:

SubagentStop:

PreCompact:
  - matcher: "auto"
    actions:
      - type: output
        message: "直前の作業内容と最初の依頼内容は圧縮しないこと。過去の作業途中の内容を圧縮"

SessionStart:

SessionEnd:
