const g:base_dir = '<script>:p:h'->expand()
const g:rc_dir = $'{g:base_dir}/rc'
const g:exrc_dir = $'{g:base_dir}/exrc'

execute $'source {g:rc_dir}/options.vim'
execute $'source {g:rc_dir}/keymaps.vim'
execute $'source {g:rc_dir}/autocmds.vim'
execute $'source {g:exrc_dir}/cache.vim'

colorscheme habamax

filetype plugin indent on
syntax on
