vim9script

const g:base_dir = '$XDG_CONFIG_HOME/vim'->expand()
const g:hooks_dir = $'{g:base_dir}/hooks'
g:hooks_dir->setenv("HOOKS_DIR")
const g:snippet_dir = $'{g:base_dir}/snippets'
const g:rc_dir = $'{g:base_dir}/rc'
const g:toml_dir = $'{g:base_dir}/toml'
const g:dpp_cache = '$XDG_CACHE_HOME/dpp_vim9'->expand()
augroup RcAutocmds
  autocmd!
augroup END

# ~/.config/vim/autoload/user/dpp.vim
import autoload $'{g:base_dir}/autoload/user/dpp.vim' as user_dpp
user_dpp.Setup()

colorscheme sorbet

filetype plugin indent on
syntax enable
