[[plugins]]
repo = 'github.com/Shougo/ddt.vim'
depends = ['denops.vim']
hooks_file = '$HOOKS_DIR/ddt/hook.lua'
on_func = 'ddt#start'

[[plugins]]
repo = 'github.com/Shougo/ddt-ui-shell'
hooks_file = '$HOOKS_DIR/ddt/shell.lua'
on_source = 'ddt.vim'

[[plugins]]
repo = 'github.com/Shougo/ddt-ui-terminal'
hooks_file = '$HOOKS_DIR/ddt/terminal.lua'
on_source = 'ddt.vim'
