[[plugins]]
repo = 'github.com/Shougo/ddt.vim'
depends = ['denops.vim', 'ddt-ui-shell']
hooks_file = '$HOOKS_DIR/ddt/hook.lua'
lazy = false

[[plugins]]
repo = 'github.com/Shougo/ddt-ui-shell'
hooks_file = '$HOOKS_DIR/ddt/shell.lua'
lazy = false
