# Filetype plugins

[[plugins]] # plantuml-syntax
repo = 'github.com/aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]] # vim-maketable
repo = 'github.com/mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]] # previm
repo = 'github.com/previm/previm'
on_ft = 'markdown'
on_cmd = 'PrevimOpen'
on_func = ['previm#refresh']
hooks_file = '$HOOKS_DIR/previm/previm.lua'

[[plugins]] # tsnode-marker.nvim
repo = 'github.com/atusy/tsnode-marker.nvim'
on_ft = 'markdown'
hooks_file = '$HOOKS_DIR/tsnode_marker.lua'
if = false

# For LISP {{{
[[plugins]]
repo = 'github.com/eraserhd/parinfer-rust'
on_ft = [
  'carp',
  'clojure',
  'dune',
  'fennel',
  'hy',
  'janet',
  'lisp',
  'racket',
  'scheme',
  'wast',
  'yuck',
]
build = 'cargo build --release > /dev/null'
hooks_file = '$HOOKS_DIR/parinfer-rust.lua'

[[plugins]]
repo = 'github.com/liquidz/vim-iced'
on_ft = 'clojure'
hooks_file = '$HOOKS_DIR/vim-iced.lua'
depends = 'github.com/guns/vim-sexp'

[[plugins]]
repo = 'github.com/guns/vim-sexp'
# }}}
