[[plugins]] # vimhelpgenerator
repo = 'github.com/LeafCage/vimhelpgenerator'
on_cmd = ['VimHelpGenerator', 'VimHelpGeneratorVirtual']
lua_source = '''
vim.g.vimhelpgenerator_author = [[yasunori0418]]
vim.g.vimhelpgenerator_uri = [[https://github.com/yasunori0418]]
'''

[[plugins]] # helpful.vim
repo = 'github.com/tweekmonster/helpful.vim'
on_cmd = 'HelpfulVersion'

[[plugins]] # suda.vim
repo = 'github.com/lambdalisue/vim-suda'
on_cmd = ['SudaRead', 'SudaWrite']

[[plugins]] # memolist.vim
repo = 'github.com/glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList', 'MemoNewWithMeta', 'MemoGrep']
lua_source = '''
vim.g.memolist_path = vim.fn.expand('~/Documents/memo')
'''

[[plugins]]
repo = 'github.com/tyru/capture.vim'
on_cmd = ['Capture']

[[plugins]] # vim-startuptime
repo = 'github.com/dstein64/vim-startuptime'
on_cmd = 'StartupTime'
lua_source = '''
-- vim.g.startuptime_tries = 10
vim.g.startuptime_event_width = 0
'''

[[plugins]] # vim-themis
repo = 'github.com/thinca/vim-themis'
on_cmd = 'StartThemis'
lua_add = '''
vim.api.nvim_create_user_command("StartThemis", function()
  require("dpp").source("vim-themis")
end, {})
'''

[[plugins]]
repo = 'github.com/nvim-tree/nvim-web-devicons'
on_lua = 'nvim-web-devicons'
hooks_file = '$HOOKS_DIR/devicons.lua'

[[plugins]]
repo = 'github.com/rickhowe/wrapwidth'
on_cmd = 'Wrapwidth'

[[plugins]]
repo = 'github.com/thinca/vim-showtime'
on_cmd = ['ShowtimeStart', 'ShowtimeResume']

[[plugins]]
repo = 'github.com/itchyny/calendar.vim'
on_cmd = 'Calendar'

[[plugins]] # for skkeleton
repo = 'github.com/skk-dev/dict'
if = false

[[plugins]] # for skkeleton
repo = 'github.com/tokuhirom/jawiki-kana-kanji-dict'
if = false

[[plugins]]
repo = 'github.com/nvim-lua/plenary.nvim'
