[[plugins]] # nvim-treesitter
repo = 'github.com/nvim-treesitter/nvim-treesitter'
rev = "main"
hooks_file = '$HOOKS_DIR/treesitter.lua'
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = 'github.com/nvim-treesitter/nvim-treesitter-textobjects'
rev = "main"
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/ts_textobjects.lua'

[[plugins]]
repo = 'github.com/shellRaining/hlchunk.nvim'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/hlchunk.lua'

[[plugins]] # matchparen.nvim
repo = 'github.com/monkoose/matchparen.nvim'
on_source = 'nvim-treesitter'
lua_source = '''
require('matchparen').setup()
'''

[[plugins]]
repo = 'github.com/JoosepAlviste/nvim-ts-context-commentstring'

[[plugins]]
repo = 'github.com/RRethy/vim-illuminate'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/illuminate.lua'

