vim9script

augroup RcAutocmds
  autocmd!
augroup END

# ~/.config/vim/autoload/user/dpp.vim
import autoload '$XDG_CONFIG_HOME/vim/autoload/user/dpp.vim'->expand() as user_dpp
user_dpp.Setup()

filetype plugin indent on
syntax enable
