# Generated by OrbStack.
# This WILL be overwritten in the future. Make a copy and update the include
# in configuration.nix if you want to keep your changes.

{ lib, config, ... }:

{
  # Add OrbStack CLI tools to PATH
  environment.shellInit = ''
    # add your customizations here
    . /opt/orbstack-guest/etc/profile-early
    . /opt/orbstack-guest/etc/profile-late
  '';

  # Enable documentation
  documentation = {
    man.enable = true;
    doc.enable = true;
    info.enable = true;
  };

  # Disable systemd-resolved
  services.resolved.enable = false;
  environment.etc."resolv.conf".source = "/opt/orbstack-guest/etc/resolv.conf";

  # Faster DHCP - OrbStack uses SLAAC exclusively
  networking.dhcpcd.extraConfig = ''
    noarp
    noipv6
  '';

  # Disable sshd
  services.openssh.enable = false;

  # systemd
  systemd.services = {
    "systemd-oomd".serviceConfig.WatchdogSec = 0;
    "systemd-userdbd".serviceConfig.WatchdogSec = 0;
    "systemd-udevd".serviceConfig.WatchdogSec = 0;
    "systemd-timesyncd".serviceConfig.WatchdogSec = 0;
    "systemd-timedated".serviceConfig.WatchdogSec = 0;
    "systemd-portabled".serviceConfig.WatchdogSec = 0;
    "systemd-nspawn@".serviceConfig.WatchdogSec = 0;
    "systemd-machined".serviceConfig.WatchdogSec = 0;
    "systemd-localed".serviceConfig.WatchdogSec = 0;
    "systemd-logind".serviceConfig.WatchdogSec = 0;
    "systemd-journald@".serviceConfig.WatchdogSec = 0;
    "systemd-journald".serviceConfig.WatchdogSec = 0;
    "systemd-journal-remote".serviceConfig.WatchdogSec = 0;
    "systemd-journal-upload".serviceConfig.WatchdogSec = 0;
    "systemd-importd".serviceConfig.WatchdogSec = 0;
    "systemd-hostnamed".serviceConfig.WatchdogSec = 0;
    "systemd-homed".serviceConfig.WatchdogSec = 0;
    "systemd-networkd".serviceConfig.WatchdogSec = lib.mkIf config.systemd.network.enable 0;
  };

  # ssh config
  programs.ssh.extraConfig = ''
    Include /opt/orbstack-guest/etc/ssh_config
  '';

  # indicate builder support for emulated architectures
  nix.settings.extra-platforms = [
    "x86_64-linux"
    "i686-linux"
  ];
}
