[general]
live_config_reload = true
working_directory = "None"
ipc_socket = true
import = [
  "~/.config/alacritty/os.toml",
  "~/.config/alacritty/nord.toml",
  "~/.config/alacritty/keybinds/base.toml",
  "~/.config/alacritty/keybinds/vi_mode.toml",
  "~/.config/alacritty/keybinds/search_mode.toml",
]

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
# decorations = "None"
opacity = 0.75
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "Off"

[terminal]
shell = "zellij"
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false

[hints]
alphabet = "jfkdls;ahgurieowpq"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
