#!/usr/bin/env bash

### Font ###
Font="Moralerspace Argon NF"

### nord colorscheme ###
# refer: https://www.nordtheme.com/docs/colors-and-palettes
## Polar Night ##
nord00="2E3440" #2E3440
nord01="3B4252" #3B4252
# nord02="434C5E" #434C5E
nord03="4C566A" #4C566A
## Snow Strom ##
nord04="D8DEE9" #D8DEE9
# nord05="E5E9F0" #E5E9F0
# nord06="ECEFF4" #ECEFF4
## Frost ##
# nord07="8FBCBB" #8FBCBB
# nord08="88C0D0" #88C0D0
# nord09="81A1C1" #81A1C1
# nord10="5E81AC" #5E81AC
## Aurora ##
# nord11="BF616A" #BF616A
# nord12="D08770" #D08770
# nord13="EBCB8B" #EBCB8B
# nord14="A3BE8C" #A3BE8C
# nord15="B48EAD" #B48EAD

SEESROUGH="0x00000000"

# alpha value
# refer: https://qiita.com/CUTBOSS/items/6166cf79b9f18c45a010
# alpha000="00"
# alpha010="1A"
# alpha020="33"
# alpha030="4D"
# alpha040="66"
alpha050="80"
# alpha060="99"
# alpha070="B3"
alpha080="CC"
# alpha090="E6"
alpha100="FF"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar_property=(
  color="0x${alpha080}${nord01}"
  border_color="0x${alpha050}${nord00}"
  position=top
  height=40
  margin=0
  y_offset=0
  corner_radius=0
  border_width=3
  blur_radius=30
  padding_left=0
  padding_right=0
  notch_width=200
  notch_offset=0
  display=all
  hidden=off
  topmost=off
  sticky=on
  font_smoothing=on
  shadow=on
)

sketchybar --bar "${bar_property[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font.family="${Font}"
  icon.font.style=Bold
  icon.font.size=17.0
  label.font.family="${Font}"
  label.font.style=Bold
  label.font.size=14.0
  icon.color="0x${alpha100}${nord04}"
  label.color="0x${alpha100}${nord04}"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("1| " "2| " "3| " "4| " "5| " "6| " "7|󰎄 " "8| ")
for i in "${!SPACE_ICONS[@]}" ; do
  sid="$((i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=5
    icon.padding_right=5
    background.color="0x${alpha100}${nord03}"
    background.corner_radius=5
    background.height=25
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Center Items #####
# We add some regular items to the center of the bar,
# where only the properties deviating from the current defaults need to be set

front_app=(
  front_app
  icon.drawing=off
  script="$PLUGIN_DIR/front_app.sh"
  --subscribe
  front_app
  front_app_switched
)
sketchybar --add item front_app center --set "${front_app[@]}"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

clock=(
  update_freq=10
  icon=
  script="$PLUGIN_DIR/clock.sh"
)
volume=(
  script="$PLUGIN_DIR/volume.sh"
  --subscribe
  volume
  volume_change
)
battery=(
  update_freq=120
  script="$PLUGIN_DIR/battery.sh"
  --subscribe
  battery
  system_woke
  power_source_change
)

sketchybar --add item clock right --set clock "${clock[@]}" \
           --add item volume right --set volume "${volume[@]}" \
           --add item battery right --set battery "${battery[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

# vim:ft=bash
