local opts = { silent = true, noremap = true }

local keymaps = {
  { mode = {"n", "x"}, lhs = "s", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = "S", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = "t", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = "T", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = "m", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = "'", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = "`", rhs = "", opts = opts },
  { mode = {"n", "x"}, lhs = " ", rhs = "", opts = opts },
  { mode = {"", "!"}, lhs = "<Left>", rhs = "", opts = opts },
  { mode = {"", "!"}, lhs = "<Down>", rhs = "", opts = opts },
  { mode = {"", "!"}, lhs = "<Up>", rhs = "", opts = opts },
  { mode = {"", "!"}, lhs = "<Right>", rhs = "", opts = opts },
  { mode = {"n"}, lhs = " w", rhs = "<Plug>(Window)", opts = {} },
  { mode = {"n"}, lhs = "<Plug>(Window)w", rhs = "<Cmd>write<CR>", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)h", rhs = "<C-W>h", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)j", rhs = "<C-W>j", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)k", rhs = "<C-W>k", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)l", rhs = "<C-W>l", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)H", rhs = "<C-W>H", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)J", rhs = "<C-W>J", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)K", rhs = "<C-W>K", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)L", rhs = "<C-W>L", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)q", rhs = "<C-W>q", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)s", rhs = "<C-W>s", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)v", rhs = "<C-W>v", opts = opts },
  { mode = {"n"}, lhs = "<Plug>(Window)n", rhs = "<C-W>n", opts = opts },
  { mode = {"n"}, lhs = "<S-Left>", rhs = "<C-w><", opts = opts },
  { mode = {"n"}, lhs = "<S-Right>", rhs = "<C-w>>", opts = opts },
  { mode = {"n"}, lhs = "<S-Up>", rhs = "<C-w>-", opts = opts },
  { mode = {"n"}, lhs = "<S-Down>", rhs = "<C-w>+", opts = opts },
  { mode = {"n"}, lhs = "[t", rhs = "gT", opts = opts },
  { mode = {"n"}, lhs = "]t", rhs = "gt", opts = opts },
  { mode = {"n"}, lhs = "[T", rhs = "<Cmd>tabfirst<CR>", opts = opts },
  { mode = {"n"}, lhs = "]T", rhs = "<Cmd>tablast<CR>", opts = opts },
  { mode = {"n"}, lhs = "tn", rhs = "<Cmd>tabnew<CR>", opts = opts },
  { mode = {"n"}, lhs = "tt", rhs = "<C-W>g<Tab>", opts = opts },
  { mode = {"n"}, lhs = "tT", rhs = "<C-W>T", opts = opts },
  { mode = {"n"}, lhs = " l", rhs = "<Plug>(lsp)", opts = {} },
}

for _, keymap in pairs(keymaps) do
  vim.keymap.set(keymap.mode, keymap.lhs, keymap.rhs, keymap.opts)
end
